//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class UFramework_BaseUnityBehaviourWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(UFramework.BaseUnityBehaviour), typeof(UFramework.BaseBehaviour));
		L.RegFunction("LateUpdate", new LuaCSFunction(LateUpdate));
		L.RegFunction("FixedUpdate", new LuaCSFunction(FixedUpdate));
		L.RegFunction("ApplicationQuit", new LuaCSFunction(ApplicationQuit));
		L.RegFunction("__tostring", new LuaCSFunction(ToLua.op_ToString));
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int LateUpdate(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			UFramework.BaseUnityBehaviour obj = (UFramework.BaseUnityBehaviour)ToLua.CheckObject<UFramework.BaseUnityBehaviour>(L, 1);
			obj.LateUpdate();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int FixedUpdate(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			UFramework.BaseUnityBehaviour obj = (UFramework.BaseUnityBehaviour)ToLua.CheckObject<UFramework.BaseUnityBehaviour>(L, 1);
			obj.FixedUpdate();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ApplicationQuit(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			UFramework.BaseUnityBehaviour obj = (UFramework.BaseUnityBehaviour)ToLua.CheckObject<UFramework.BaseUnityBehaviour>(L, 1);
			obj.ApplicationQuit();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

