//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class UFramework_BaseManagerWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(UFramework.BaseManager), typeof(UFramework.BaseBehaviour));
		L.RegFunction("__tostring", new LuaCSFunction(ToLua.op_ToString));
		L.EndClass();
	}
}

