//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class UFramework_BaseBehaviourWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(UFramework.BaseBehaviour), typeof(System.Object));
		L.RegFunction("Initialize", new LuaCSFunction(Initialize));
		L.RegFunction("Update", new LuaCSFunction(Update));
		L.RegFunction("Dispose", new LuaCSFunction(Dispose));
		L.RegFunction("__tostring", new LuaCSFunction(ToLua.op_ToString));
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Initialize(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			UFramework.BaseBehaviour obj = (UFramework.BaseBehaviour)ToLua.CheckObject<UFramework.BaseBehaviour>(L, 1);
			obj.Initialize();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Update(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UFramework.BaseBehaviour obj = (UFramework.BaseBehaviour)ToLua.CheckObject<UFramework.BaseBehaviour>(L, 1);
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			obj.Update(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Dispose(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			UFramework.BaseBehaviour obj = (UFramework.BaseBehaviour)ToLua.CheckObject<UFramework.BaseBehaviour>(L, 1);
			obj.Dispose();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

