//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class UFramework_Core_ProtocalTypeWrap
{
	public static void Register(LuaState L)
	{
		L.BeginEnum(typeof(UFramework.Core.ProtocalType));
		L.RegVar("Binary", new LuaCSFunction(get_Binary), null);
		L.RegVar("SizeBinary", new LuaCSFunction(get_SizeBinary), null);
		L.RegVar("SizeHeaderBinary", new LuaCSFunction(get_SizeHeaderBinary), null);
		L.RegFunction("IntToEnum", new LuaCSFunction(IntToEnum));
		L.EndEnum();
		TypeTraits<UFramework.Core.ProtocalType>.Check = CheckType;
		StackTraits<UFramework.Core.ProtocalType>.Push = Push;
	}

	static void Push(IntPtr L, UFramework.Core.ProtocalType arg)
	{
		ToLua.Push(L, arg);
	}

	static Type TypeOf_UFramework_Core_ProtocalType = typeof(UFramework.Core.ProtocalType);

	static bool CheckType(IntPtr L, int pos)
	{
		return TypeChecker.CheckEnumType(TypeOf_UFramework_Core_ProtocalType, L, pos);
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Binary(IntPtr L)
	{
		ToLua.Push(L, UFramework.Core.ProtocalType.Binary);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_SizeBinary(IntPtr L)
	{
		ToLua.Push(L, UFramework.Core.ProtocalType.SizeBinary);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_SizeHeaderBinary(IntPtr L)
	{
		ToLua.Push(L, UFramework.Core.ProtocalType.SizeHeaderBinary);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IntToEnum(IntPtr L)
	{
		int arg0 = (int)LuaDLL.lua_tointeger(L, 1);
		UFramework.Core.ProtocalType o = (UFramework.Core.ProtocalType)arg0;
		ToLua.Push(L, o);
		return 1;
	}
}

